services:
  app:
    build: .
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: mysql://root:Sm4rtCod3x$@certixdb.cj04oa2g0ew8.ap-southeast-1.rds.amazonaws.com:3306/apigtw
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npx nodemon index.js

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Sm4rtCod3x$
      MYSQL_DATABASE: apigtw
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
